# Generated by Django 5.2.12 on 2026-03-14 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('clinica', models.CharField(max_length=200)),
                ('fecha_consulta', models.DateField()),
                ('diagnostico', models.TextField()),
                ('documento_respaldo', models.FileField(blank=True, null=True, upload_to='clinico/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('miligramos', models.FloatField(blank=True, null=True)),
                ('frecuencia_horas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('duracion_dias', models.IntegerField()),
                ('es_cronico', models.BooleanField(default=False)),
                ('raw_extraction_data', models.JSONField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='registros.registroclinico')),
            ],
        ),
    ]
