# Generated by Django 5.2.12 on 2026-03-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroclinico',
            options={'ordering': ['-fecha_consulta']},
        ),
    ]
