# Generated by Django 5.2.12 on 2026-03-15 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registroclinico_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('radiografia', 'Radiografía'), ('analisis', 'Análisis/Laboratorio'), ('ecografia', 'Ecografía'), ('tomografia', 'Tomografía'), ('resonancia', 'Resonancia Magnética'), ('informe', 'Informe Médico'), ('receta', 'Receta Médica'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos_medicos/%Y/%m/%d/')),
                ('fecha_documento', models.DateField(blank=True, help_text='Fecha del documento original', null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido_extraido', models.TextField(blank=True, help_text='Contenido extraído mediante OCR/IA', null=True)),
                ('ia_analisis', models.JSONField(blank=True, help_text='Análisis IA (MedSigLIP, MedGemma)', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_medicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_documento', '-creado_en'],
                'indexes': [models.Index(fields=['usuario', '-creado_en'], name='registros_m_usuario_1e181a_idx'), models.Index(fields=['tipo_documento'], name='registros_m_tipo_do_59c6b7_idx')],
            },
        ),
    ]
